### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by jeansalac** [scratchblocks/scratchblocks#250]
I tried using the Node port and got this error when running `node test.js>foo.xml`:
```/home/salac/scratchblocks/build/scratchblocks.min.js:2
"use strict";function makeCanvas(){return document.createElement("canvas")}var scratchblocks=window.scratchblocks=module.exports=require("./scratch2/")(window,makeCanvas),style=scratchblocks.makeStyle();document.head.appendChild(style);
                                                                                             ^
ReferenceError: window is not defined
    at Object.1../scratch2/ (/home/salac/scratchblocks/build/scratchblocks.min.js:2:94)
    at o (/home/salac/scratchblocks/build/scratchblocks.min.js:1:700)
    at r (/home/salac/scratchblocks/build/scratchblocks.min.js:1:866)
    at /home/salac/scratchblocks/build/scratchblocks.min.js:1:895
    at /home/salac/scratchblocks/build/scratchblocks.min.js:1:150
    at Object.<anonymous> (/home/salac/scratchblocks/build/scratchblocks.min.js:1:391)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12) ```

**Comment by tjvr** [comment]
Hey, I'm afraid the Node port isn't supported anymore. If you want to render scratchblocks on the backend, I recommend using something like Phantom.js or Puppeteer :-)
